/* AUTO-GENERATED by scripts/generate-financial-backend-adapter.mjs. DO NOT EDIT. */
export const GENERATED_BACKEND_REGISTRY = {
  "rubrics": {
    "ativo_circulante_caixa": {
      "canonical_key": "ativo_circulante_caixa",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo circulante",
      "presentation_order": 10,
      "display_label": "Caixa e Equivalentes de Caixa",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "cash",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_circulante_aplicacoes_liquidez_imediata": {
      "canonical_key": "ativo_circulante_aplicacoes_liquidez_imediata",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo circulante",
      "presentation_order": 15,
      "display_label": "Aplicações Financeiras de Liquidez Imediata",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "cash",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_circulante_receber": {
      "canonical_key": "ativo_circulante_receber",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo circulante",
      "presentation_order": 20,
      "display_label": "Contas a Receber",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "operating_asset",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_circulante_estoques": {
      "canonical_key": "ativo_circulante_estoques",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo circulante",
      "presentation_order": 30,
      "display_label": "Estoques",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "operating_asset",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_circulante_impostos": {
      "canonical_key": "ativo_circulante_impostos",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo circulante",
      "presentation_order": 40,
      "display_label": "Impostos a Recuperar",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "operating_asset",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_circulante_biologicos": {
      "canonical_key": "ativo_circulante_biologicos",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo circulante",
      "presentation_order": 50,
      "display_label": "Ativos Biológicos",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "operating_asset",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_circulante_outros": {
      "canonical_key": "ativo_circulante_outros",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo circulante",
      "presentation_order": 60,
      "display_label": "Outros Créditos",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "operating_asset",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_nc_aplicacoes": {
      "canonical_key": "ativo_nc_aplicacoes",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo não circulante",
      "presentation_order": 10,
      "display_label": "Aplicações Financeiras",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "requires_review",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_nc_receber_lp": {
      "canonical_key": "ativo_nc_receber_lp",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo não circulante",
      "presentation_order": 20,
      "display_label": "Contas a Receber LP",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "requires_review",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_nc_impostos_lp": {
      "canonical_key": "ativo_nc_impostos_lp",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo não circulante",
      "presentation_order": 30,
      "display_label": "Impostos a Recuperar LP",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "requires_review",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_nc_impostos_diferidos": {
      "canonical_key": "ativo_nc_impostos_diferidos",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo não circulante",
      "presentation_order": 40,
      "display_label": "Impostos Diferidos",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "requires_review",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_nc_outros_creditos": {
      "canonical_key": "ativo_nc_outros_creditos",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo não circulante",
      "presentation_order": 50,
      "display_label": "Outros Créditos LP",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "requires_review",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_nc_investimentos": {
      "canonical_key": "ativo_nc_investimentos",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo não circulante",
      "presentation_order": 60,
      "display_label": "Investimentos",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "investing",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_nc_direitos_uso": {
      "canonical_key": "ativo_nc_direitos_uso",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo não circulante",
      "presentation_order": 70,
      "display_label": "Direitos de Uso",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "investing",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_nao_circulante": {
      "canonical_key": "ativo_nao_circulante",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo não circulante",
      "presentation_order": 80,
      "display_label": "Imobilizado",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "investing",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "ativo_nc_intangivel": {
      "canonical_key": "ativo_nc_intangivel",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Ativo não circulante",
      "presentation_order": 90,
      "display_label": "Intangível",
      "normal_balance": "debit",
      "presentation_sign": "positive",
      "dfc_treatment": "investing",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": 1,
      "credit_presentation_effect": -1
    },
    "passivo_circulante_trabalhistas": {
      "canonical_key": "passivo_circulante_trabalhistas",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo circulante",
      "presentation_order": 10,
      "display_label": "Obrigações Trabalhistas",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "operating_liability",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "passivo_circulante_fiscais": {
      "canonical_key": "passivo_circulante_fiscais",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo circulante",
      "presentation_order": 20,
      "display_label": "Obrigações Fiscais",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "operating_liability",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "passivo_circulante_fornecedores": {
      "canonical_key": "passivo_circulante_fornecedores",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo circulante",
      "presentation_order": 30,
      "display_label": "Fornecedores",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "operating_liability",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "passivo_circulante_emprestimos": {
      "canonical_key": "passivo_circulante_emprestimos",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo circulante",
      "presentation_order": 40,
      "display_label": "Empréstimos e Financiamentos",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "financing",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "passivo_circulante_imoveis": {
      "canonical_key": "passivo_circulante_imoveis",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo circulante",
      "presentation_order": 50,
      "display_label": "Obrig. por Aquisição de Imóveis",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "requires_review",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "passivo_circulante_arrendamentos": {
      "canonical_key": "passivo_circulante_arrendamentos",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo circulante",
      "presentation_order": 60,
      "display_label": "Arrendamentos a Pagar",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "financing",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "passivo_circulante_adiantamentos": {
      "canonical_key": "passivo_circulante_adiantamentos",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo circulante",
      "presentation_order": 70,
      "display_label": "Adiantamentos de Clientes",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "operating_liability",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "passivo_circulante_outros": {
      "canonical_key": "passivo_circulante_outros",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo circulante",
      "presentation_order": 80,
      "display_label": "Outras Contas a Pagar",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "operating_liability",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "passivo_nao_circulante": {
      "canonical_key": "passivo_nao_circulante",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo não circulante",
      "presentation_order": 10,
      "display_label": "Empréstimos e Financiamentos LP",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "financing",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "passivo_nc_imoveis_lp": {
      "canonical_key": "passivo_nc_imoveis_lp",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo não circulante",
      "presentation_order": 20,
      "display_label": "Obrig. por Aquisição de Imóveis LP",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "requires_review",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "passivo_nc_arrendamentos_lp": {
      "canonical_key": "passivo_nc_arrendamentos_lp",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Passivo não circulante",
      "presentation_order": 30,
      "display_label": "Arrendamentos a Pagar LP",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "financing",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "patrimonio_capital": {
      "canonical_key": "patrimonio_capital",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Patrimônio líquido",
      "presentation_order": 10,
      "display_label": "Capital Social",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "financing",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "patrimonio_reservas": {
      "canonical_key": "patrimonio_reservas",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Patrimônio líquido",
      "presentation_order": 20,
      "display_label": "Reservas",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "requires_review",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "patrimonio_reservas_fiscais": {
      "canonical_key": "patrimonio_reservas_fiscais",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Patrimônio líquido",
      "presentation_order": 30,
      "display_label": "Reserva de Incentivos Fiscais",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "requires_review",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "patrimonio_liquido": {
      "canonical_key": "patrimonio_liquido",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Patrimônio líquido",
      "presentation_order": 40,
      "display_label": "Lucros Acumulados",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "ignored",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "patrimonio_prejuizos": {
      "canonical_key": "patrimonio_prejuizos",
      "statement_code": "BP",
      "line_type": "source",
      "family": "balance_sheet",
      "presentation_group": "Patrimônio líquido",
      "presentation_order": 50,
      "display_label": "Prejuízos Acumulados",
      "normal_balance": "debit",
      "presentation_sign": "negative",
      "dfc_treatment": "ignored",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "receita_bruta": {
      "canonical_key": "receita_bruta",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Receita",
      "presentation_order": 10,
      "display_label": "Receita Bruta",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "deducoes_tributarias": {
      "canonical_key": "deducoes_tributarias",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Receita",
      "presentation_order": 20,
      "display_label": "(-) Deduções Tributárias",
      "normal_balance": "debit",
      "presentation_sign": "negative",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "devolucoes_abatimentos": {
      "canonical_key": "devolucoes_abatimentos",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Receita",
      "presentation_order": 30,
      "display_label": "(-) Devoluções e Abatimentos",
      "normal_balance": "debit",
      "presentation_sign": "negative",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "custo_produtos": {
      "canonical_key": "custo_produtos",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Custo",
      "presentation_order": 10,
      "display_label": "(-) Custo",
      "normal_balance": "debit",
      "presentation_sign": "negative",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "despesas_gerais_admin": {
      "canonical_key": "despesas_gerais_admin",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Despesas operacionais",
      "presentation_order": 10,
      "display_label": "(-) Gerais e Administrativas",
      "normal_balance": "debit",
      "presentation_sign": "negative",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "despesas_comerciais": {
      "canonical_key": "despesas_comerciais",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Despesas operacionais",
      "presentation_order": 20,
      "display_label": "(-) Comerciais",
      "normal_balance": "debit",
      "presentation_sign": "negative",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "outras_receitas_despesas": {
      "canonical_key": "outras_receitas_despesas",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Despesas operacionais",
      "presentation_order": 30,
      "display_label": "(+/-) Outras Receitas e Despesas",
      "normal_balance": "mixed",
      "presentation_sign": "formula",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "journal_effect_rule": "explicit",
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "depreciacao_amortizacao": {
      "canonical_key": "depreciacao_amortizacao",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Despesas operacionais",
      "presentation_order": 40,
      "display_label": "(-) Depreciação e Amortização",
      "normal_balance": "debit",
      "presentation_sign": "negative",
      "dfc_treatment": "non_cash_adjustment",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "receitas_financeiras": {
      "canonical_key": "receitas_financeiras",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Resultado financeiro",
      "presentation_order": 10,
      "display_label": "(+) Receitas Financeiras",
      "normal_balance": "credit",
      "presentation_sign": "positive",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "despesas_financeiras": {
      "canonical_key": "despesas_financeiras",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Resultado financeiro",
      "presentation_order": 20,
      "display_label": "(-) Despesas Financeiras",
      "normal_balance": "debit",
      "presentation_sign": "negative",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "ir_csll": {
      "canonical_key": "ir_csll",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Impostos",
      "presentation_order": 10,
      "display_label": "(-) Imposto de Renda e CSLL — Correntes",
      "normal_balance": "debit",
      "presentation_sign": "negative",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    },
    "ir_diferido": {
      "canonical_key": "ir_diferido",
      "statement_code": "DRE",
      "line_type": "source",
      "family": "dre",
      "presentation_group": "Impostos",
      "presentation_order": 20,
      "display_label": "(-) Imposto de Renda e CSLL — Diferidos",
      "normal_balance": "debit",
      "presentation_sign": "negative",
      "dfc_treatment": "indirect_result_component",
      "active": true,
      "classification": "SOURCE_CANONICAL_RUBRIC",
      "elimination_eligible": true,
      "debit_presentation_effect": -1,
      "credit_presentation_effect": 1
    }
  },
  "calculated": {
    "receita_liquida": {
      "canonical_key": "receita_liquida",
      "statement_code": "DRE",
      "line_type": "calculated",
      "family": "dre",
      "presentation_group": "Receita",
      "presentation_order": 200,
      "display_label": "Receita Líquida",
      "operands": [
        "receita_bruta",
        "deducoes_tributarias",
        "devolucoes_abatimentos"
      ],
      "coefficients": [
        1,
        1,
        1
      ],
      "formula_desc": "Receita Bruta + Deduções + Devoluções",
      "active": true
    },
    "custos": {
      "canonical_key": "custos",
      "statement_code": "DRE",
      "line_type": "calculated",
      "family": "dre",
      "presentation_group": "Custo",
      "presentation_order": 190,
      "display_label": "Custos",
      "operands": [
        "custo_produtos"
      ],
      "coefficients": [
        1
      ],
      "formula_desc": "Custo de mercadorias, produtos e serviços",
      "active": true
    },
    "lucro_bruto": {
      "canonical_key": "lucro_bruto",
      "statement_code": "DRE",
      "line_type": "calculated",
      "family": "dre",
      "presentation_group": "Custo",
      "presentation_order": 200,
      "display_label": "Lucro Bruto",
      "operands": [
        "receita_liquida",
        "custos"
      ],
      "coefficients": [
        1,
        1
      ],
      "formula_desc": "Receita Líquida + Custos",
      "active": true
    },
    "despesas_operacionais": {
      "canonical_key": "despesas_operacionais",
      "statement_code": "DRE",
      "line_type": "calculated",
      "family": "dre",
      "presentation_group": "Despesas operacionais",
      "presentation_order": 190,
      "display_label": "Despesas Operacionais",
      "operands": [
        "despesas_gerais_admin",
        "despesas_comerciais",
        "outras_receitas_despesas",
        "depreciacao_amortizacao"
      ],
      "coefficients": [
        1,
        1,
        1,
        1
      ],
      "formula_desc": "Soma das despesas operacionais",
      "active": true
    },
    "ebit": {
      "canonical_key": "ebit",
      "statement_code": "DRE",
      "line_type": "calculated",
      "family": "dre",
      "presentation_group": "Despesas operacionais",
      "presentation_order": 200,
      "display_label": "EBIT",
      "operands": [
        "lucro_bruto",
        "despesas_operacionais"
      ],
      "coefficients": [
        1,
        1
      ],
      "formula_desc": "Lucro Bruto + Despesas Operacionais",
      "active": true
    },
    "ebitda": {
      "canonical_key": "ebitda",
      "statement_code": "DRE",
      "line_type": "calculated",
      "family": "dre",
      "presentation_group": "Despesas operacionais",
      "presentation_order": 210,
      "display_label": "EBITDA",
      "operands": [
        "ebit",
        "depreciacao_amortizacao"
      ],
      "coefficients": [
        1,
        -1
      ],
      "formula_desc": "EBIT - Depreciação e Amortização",
      "active": true
    },
    "resultado_financeiro": {
      "canonical_key": "resultado_financeiro",
      "statement_code": "DRE",
      "line_type": "calculated",
      "family": "dre",
      "presentation_group": "Resultado financeiro",
      "presentation_order": 200,
      "display_label": "Resultado Financeiro",
      "operands": [
        "receitas_financeiras",
        "despesas_financeiras"
      ],
      "coefficients": [
        1,
        1
      ],
      "formula_desc": "Receitas Financeiras + Despesas Financeiras",
      "active": true
    },
    "resultado_antes_ir_csll": {
      "canonical_key": "resultado_antes_ir_csll",
      "statement_code": "DRE",
      "line_type": "calculated",
      "family": "dre",
      "presentation_group": "Resultado financeiro",
      "presentation_order": 300,
      "display_label": "Resultado Antes de IR/CSLL",
      "operands": [
        "ebit",
        "resultado_financeiro"
      ],
      "coefficients": [
        1,
        1
      ],
      "formula_desc": "EBIT + Resultado Financeiro",
      "active": true
    },
    "resultado_liquido": {
      "canonical_key": "resultado_liquido",
      "statement_code": "DRE",
      "line_type": "total",
      "family": "dre",
      "presentation_group": "Impostos",
      "presentation_order": 999,
      "display_label": "Resultado Líquido do Exercício",
      "operands": [
        "resultado_antes_ir_csll",
        "ir_csll",
        "ir_diferido"
      ],
      "coefficients": [
        1,
        1,
        1
      ],
      "formula_desc": "Resultado Antes IR/CSLL + IR/CSLL",
      "active": true
    }
  },
  "totals": {
    "total_ativo_circulante": {
      "canonical_key": "total_ativo_circulante",
      "statement_code": "BP",
      "line_type": "total",
      "family": "balance_sheet",
      "display_label": "Total do Ativo Circulante",
      "component_keys": [
        "ativo_circulante_caixa",
        "ativo_circulante_aplicacoes_liquidez_imediata",
        "ativo_circulante_receber",
        "ativo_circulante_estoques",
        "ativo_circulante_impostos",
        "ativo_circulante_biologicos",
        "ativo_circulante_outros"
      ],
      "active": true
    },
    "total_ativo_nao_circulante": {
      "canonical_key": "total_ativo_nao_circulante",
      "statement_code": "BP",
      "line_type": "total",
      "family": "balance_sheet",
      "display_label": "Total do Ativo Não Circulante",
      "component_keys": [
        "ativo_nc_aplicacoes",
        "ativo_nc_receber_lp",
        "ativo_nc_impostos_lp",
        "ativo_nc_impostos_diferidos",
        "ativo_nc_outros_creditos",
        "ativo_nc_investimentos",
        "ativo_nc_direitos_uso",
        "ativo_nao_circulante",
        "ativo_nc_intangivel"
      ],
      "active": true
    },
    "total_ativo": {
      "canonical_key": "total_ativo",
      "statement_code": "BP",
      "line_type": "total",
      "family": "balance_sheet",
      "display_label": "Total do Ativo",
      "component_keys": [
        "ativo_circulante_caixa",
        "ativo_circulante_aplicacoes_liquidez_imediata",
        "ativo_circulante_receber",
        "ativo_circulante_estoques",
        "ativo_circulante_impostos",
        "ativo_circulante_biologicos",
        "ativo_circulante_outros",
        "ativo_nc_aplicacoes",
        "ativo_nc_receber_lp",
        "ativo_nc_impostos_lp",
        "ativo_nc_impostos_diferidos",
        "ativo_nc_outros_creditos",
        "ativo_nc_investimentos",
        "ativo_nc_direitos_uso",
        "ativo_nao_circulante",
        "ativo_nc_intangivel"
      ],
      "active": true
    },
    "total_passivo_circulante": {
      "canonical_key": "total_passivo_circulante",
      "statement_code": "BP",
      "line_type": "total",
      "family": "balance_sheet",
      "display_label": "Total do Passivo Circulante",
      "component_keys": [
        "passivo_circulante_trabalhistas",
        "passivo_circulante_fiscais",
        "passivo_circulante_fornecedores",
        "passivo_circulante_emprestimos",
        "passivo_circulante_imoveis",
        "passivo_circulante_arrendamentos",
        "passivo_circulante_adiantamentos",
        "passivo_circulante_outros"
      ],
      "active": true
    },
    "total_passivo_nao_circulante": {
      "canonical_key": "total_passivo_nao_circulante",
      "statement_code": "BP",
      "line_type": "total",
      "family": "balance_sheet",
      "display_label": "Total do Passivo Não Circulante",
      "component_keys": [
        "passivo_nao_circulante",
        "passivo_nc_imoveis_lp",
        "passivo_nc_arrendamentos_lp"
      ],
      "active": true
    },
    "total_passivo": {
      "canonical_key": "total_passivo",
      "statement_code": "BP",
      "line_type": "total",
      "family": "balance_sheet",
      "display_label": "Total do Passivo",
      "component_keys": [
        "passivo_circulante_trabalhistas",
        "passivo_circulante_fiscais",
        "passivo_circulante_fornecedores",
        "passivo_circulante_emprestimos",
        "passivo_circulante_imoveis",
        "passivo_circulante_arrendamentos",
        "passivo_circulante_adiantamentos",
        "passivo_circulante_outros",
        "passivo_nao_circulante",
        "passivo_nc_imoveis_lp",
        "passivo_nc_arrendamentos_lp"
      ],
      "active": true
    },
    "total_patrimonio_liquido": {
      "canonical_key": "total_patrimonio_liquido",
      "statement_code": "BP",
      "line_type": "total",
      "family": "balance_sheet",
      "display_label": "Total do Patrimônio Líquido",
      "component_keys": [
        "patrimonio_capital",
        "patrimonio_reservas",
        "patrimonio_reservas_fiscais",
        "patrimonio_liquido",
        "patrimonio_prejuizos"
      ],
      "active": true
    },
    "total_passivo_patrimonio_liquido": {
      "canonical_key": "total_passivo_patrimonio_liquido",
      "statement_code": "BP",
      "line_type": "total",
      "family": "balance_sheet",
      "display_label": "Total Passivo e Patrimônio Líquido",
      "component_keys": [
        "passivo_circulante_trabalhistas",
        "passivo_circulante_fiscais",
        "passivo_circulante_fornecedores",
        "passivo_circulante_emprestimos",
        "passivo_circulante_imoveis",
        "passivo_circulante_arrendamentos",
        "passivo_circulante_adiantamentos",
        "passivo_circulante_outros",
        "passivo_nao_circulante",
        "passivo_nc_imoveis_lp",
        "passivo_nc_arrendamentos_lp",
        "patrimonio_capital",
        "patrimonio_reservas",
        "patrimonio_reservas_fiscais",
        "patrimonio_liquido",
        "patrimonio_prejuizos"
      ],
      "active": true
    }
  }
};
// BEGIN GENERATED FAL FINANCIAL ENGINE
const GENERATED_ENGINE_CONTRACT = {
  registry_version: '3.0.0',
  formula_version: 'FAL-FIN-3.0.0',
  analysis_types: ['individual', 'combined', 'consolidated'],
  indicator_codes: ['liquidez_corrente','liquidez_seca','liquidez_imediata','liquidez_geral','capital_circulante_liquido','passivo_sobre_ativo','capital_terceiros_sobre_pl','divida_liquida','divida_liquida_sobre_ebitda','composicao_endividamento','margem_bruta','margem_ebit','margem_ebitda','margem_liquida','roa','roe','giro_ativo','prazo_medio_recebimento','prazo_medio_pagamento','prazo_medio_estoque','ciclo_operacional','ciclo_financeiro','kanitz_fator_insolvencia'],
  kanitz_formula: '0.05*RPL+1.65*LG+3.55*LS-1.06*LC-0.33*PCT',
  bp_tolerance: 0.01,
  elimination_classification: 'SOURCE_CANONICAL_RUBRIC'
};
const optionalNumber = (value) => {
  if (value === null || value === undefined || value === '') return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
};
function calculateJournalPresentationEffect({ rubric, side, amount }) {
  const numericAmount = Number(amount);
  if (!Number.isFinite(numericAmount) || numericAmount <= 0) throw new Error('ELIMINATION_AMOUNT_INVALID');
  if (!['debit', 'credit'].includes(side)) throw new Error('ELIMINATION_SIDE_INVALID');
  const factor = side === 'debit' ? rubric?.debit_presentation_effect : rubric?.credit_presentation_effect;
  if (!Number.isFinite(factor)) throw new Error('ELIMINATION_JOURNAL_EFFECT_UNDEFINED');
  return numericAmount * factor;
}
const sumRequiredSources = (values, keys) => {
  const resolved = keys.map((key) => optionalNumber(values[key]));
  if (resolved.every((value) => value === null)) return null;
  return resolved.reduce((sum, value) => sum + (value ?? 0), 0);
};
const safeDivide = (numerator, denominator) => {
  const n = optionalNumber(numerator), d = optionalNumber(denominator);
  return n === null || d === null || d === 0 ? null : n / d;
};
const evaluate = (values, keys, coefficients) => {
  const resolved = keys.map((key, index) => {
    const value = optionalNumber(values[key]);
    return value === null ? null : value * (coefficients?.[index] ?? 1);
  });
  if (resolved.every((value) => value === null)) return null;
  return resolved.reduce((sum, value) => sum + (value ?? 0), 0);
};
const makeIndicator = (code, family, numerator, denominator, formula) => {
  const numeratorValue = optionalNumber(numerator);
  const hasDenominator = denominator !== undefined;
  const denominatorValue = hasDenominator ? optionalNumber(denominator) : undefined;
  const value = numeratorValue === null ? null : hasDenominator ? safeDivide(numeratorValue, denominatorValue) : numeratorValue;
  const validationCode = numeratorValue === null ? 'INDICATOR_SOURCE_UNAVAILABLE' : hasDenominator && (denominatorValue === null || denominatorValue === 0) ? 'INDICATOR_DENOMINATOR_UNAVAILABLE' : null;
  return { indicator_code: code, indicator_family: family, value, confidence_level: value === null ? 'low' : 'high', warning: validationCode, validation_code: validationCode, formula, formula_version: GENERATED_ENGINE_CONTRACT.formula_version };
};
function buildStatements(sourceValues, registry) {
  const values = {};
  for (const key of Object.keys(registry.rubrics)) values[key] = optionalNumber(sourceValues[key]);
  for (const [key, meta] of Object.entries(registry.calculated)) values[key] = evaluate(values, meta.operands, meta.coefficients);
  for (const [key, meta] of Object.entries(registry.totals)) values[key] = evaluate(values, meta.component_keys, meta.component_keys.map(() => 1));
  values.total_passivo_pl = values.total_passivo_patrimonio_liquido;
  values.resultado_operacional = values.ebit;
  values.resultado_financeiro_liquido = values.resultado_financeiro;
  values.resultado_antes_ir = values.resultado_antes_ir_csll;
  return values;
}
function calculateKanitz(v) {
  const pl = optionalNumber(v.total_patrimonio_liquido), passivo = optionalNumber(v.total_passivo);
  const realizavel = sumRequiredSources(v, ['total_ativo_circulante','ativo_nc_receber_lp','ativo_nc_impostos_lp','ativo_nc_outros_creditos']);
  const ac = optionalNumber(v.total_ativo_circulante), estoques = optionalNumber(v.ativo_circulante_estoques);
  const components = {
    rentabilidade_do_pl: safeDivide(v.resultado_liquido, pl),
    liquidez_geral: safeDivide(realizavel, passivo),
    liquidez_seca: safeDivide(ac === null || estoques === null ? null : ac - estoques, v.total_passivo_circulante),
    liquidez_corrente: safeDivide(ac, v.total_passivo_circulante),
    capital_de_terceiros_sobre_pl: safeDivide(passivo, pl)
  };
  const available = Object.values(components).every((value) => value !== null);
  const value = available ? 0.05*components.rentabilidade_do_pl + 1.65*components.liquidez_geral + 3.55*components.liquidez_seca - 1.06*components.liquidez_corrente - 0.33*components.capital_de_terceiros_sobre_pl : null;
  const sourceUnavailable = pl === null || passivo === null || optionalNumber(v.resultado_liquido) === null;
  return { value, components, confidence_level: pl === null || pl <= 0 || value === null ? 'low' : 'high', warning: sourceUnavailable ? 'INDICATOR_SOURCE_UNAVAILABLE' : pl <= 0 ? 'KANITZ_PL_NON_POSITIVE' : value === null ? 'INDICATOR_DENOMINATOR_UNAVAILABLE' : null };
}
function calculateIndicators(v) {
  const disponibilidade = sumRequiredSources(v, ['ativo_circulante_caixa','ativo_circulante_aplicacoes_liquidez_imediata']);
  const dividaBruta = sumRequiredSources(v, ['passivo_circulante_emprestimos','passivo_circulante_arrendamentos','passivo_nao_circulante','passivo_nc_arrendamentos_lp']);
  const dividaLiquida = dividaBruta === null || disponibilidade === null ? null : dividaBruta - disponibilidade;
  const realizavel = sumRequiredSources(v, ['total_ativo_circulante','ativo_nc_receber_lp','ativo_nc_impostos_lp','ativo_nc_outros_creditos']);
  const ac = optionalNumber(v.total_ativo_circulante), pc = optionalNumber(v.total_passivo_circulante), estoque = optionalNumber(v.ativo_circulante_estoques);
  const custo = optionalNumber(v.custos), custoAbs = custo === null ? null : Math.abs(custo);
  const clientes = optionalNumber(v.ativo_circulante_receber), fornecedores = optionalNumber(v.passivo_circulante_fornecedores);
  const pmr = clientes === null ? null : safeDivide(clientes * 360, v.receita_bruta);
  const pmp = fornecedores === null ? null : safeDivide(fornecedores * 360, custoAbs);
  const pme = estoque === null ? null : safeDivide(estoque * 360, custoAbs);
  const list = [
    makeIndicator('liquidez_corrente','liquidez',ac,pc,'AC / PC'), makeIndicator('liquidez_seca','liquidez',ac===null||estoque===null?null:ac-estoque,pc,'(AC - Estoques) / PC'),
    makeIndicator('liquidez_imediata','liquidez',disponibilidade,pc,'Disponibilidade imediata / PC'), makeIndicator('liquidez_geral','liquidez',realizavel,v.total_passivo,'Realizável / Passivo exigível'),
    makeIndicator('capital_circulante_liquido','capital_giro',ac===null||pc===null?null:ac-pc,undefined,'AC - PC'), makeIndicator('passivo_sobre_ativo','endividamento',v.total_passivo ?? null,v.total_ativo ?? null,'Passivo / Ativo'),
    makeIndicator('capital_terceiros_sobre_pl','estrutura_capital',v.total_passivo ?? null,v.total_patrimonio_liquido ?? null,'Passivo / PL'), makeIndicator('divida_liquida','endividamento',dividaLiquida,undefined,'Dívida bruta - disponibilidade'),
    makeIndicator('divida_liquida_sobre_ebitda','endividamento',dividaLiquida,v.ebitda ?? null,'Dívida líquida / EBITDA'), makeIndicator('composicao_endividamento','endividamento',pc,v.total_passivo ?? null,'PC / Passivo'),
    makeIndicator('margem_bruta','margens',v.lucro_bruto,v.receita_liquida ?? null,'Lucro bruto / Receita líquida'), makeIndicator('margem_ebit','margens',v.ebit,v.receita_liquida ?? null,'EBIT / Receita líquida'),
    makeIndicator('margem_ebitda','margens',v.ebitda,v.receita_liquida ?? null,'EBITDA / Receita líquida'), makeIndicator('margem_liquida','margens',v.resultado_liquido,v.receita_liquida ?? null,'Resultado líquido / Receita líquida'),
    makeIndicator('roa','rentabilidade',v.resultado_liquido,v.total_ativo ?? null,'Resultado líquido / Ativo'), makeIndicator('roe','rentabilidade',v.resultado_liquido,v.total_patrimonio_liquido ?? null,'Resultado líquido / PL'),
    makeIndicator('giro_ativo','atividade',v.receita_liquida,v.total_ativo ?? null,'Receita líquida / Ativo'), makeIndicator('prazo_medio_recebimento','atividade',pmr,undefined,'Clientes × 360 / Receita bruta'),
    makeIndicator('prazo_medio_pagamento','atividade',pmp,undefined,'Fornecedores × 360 / |Custos|'), makeIndicator('prazo_medio_estoque','atividade',pme,undefined,'Estoques × 360 / |Custos|'),
    makeIndicator('ciclo_operacional','atividade',pmr===null||pme===null?null:pmr+pme,undefined,'PMR + PME'), makeIndicator('ciclo_financeiro','atividade',pmr===null||pme===null||pmp===null?null:pmr+pme-pmp,undefined,'Ciclo operacional - PMP')
  ];
  const kanitz = calculateKanitz(v);
  list.push({ indicator_code:'kanitz_fator_insolvencia', indicator_family:'solvencia', value:kanitz.value, confidence_level:kanitz.confidence_level, warning:kanitz.warning, validation_code:kanitz.warning, formula:'0,05×RPL + 1,65×LG + 3,55×LS - 1,06×LC - 0,33×PCT', formula_version:GENERATED_ENGINE_CONTRACT.formula_version, components:kanitz.components });
  return list;
}
// END GENERATED FAL FINANCIAL ENGINE
export function executeGeneratedBackendEngine({ source_values = {}, context = {} } = {}) {
  const statements = buildStatements(source_values, GENERATED_BACKEND_REGISTRY);
  const expected = optionalNumber(statements.total_ativo);
  const actual = optionalNumber(statements.total_passivo_patrimonio_liquido);
  const difference = expected === null || actual === null ? null : Math.round(Math.abs(expected - actual) * 100) / 100;
  const balanced = difference !== null && difference <= GENERATED_ENGINE_CONTRACT.bp_tolerance;
  const code = expected === null || actual === null ? 'BP_SOURCE_UNAVAILABLE' : balanced ? null : 'BP_ACCOUNTING_EQUATION_MISMATCH';
  const bp = { ...context, expected, actual, difference, balanced, validation: balanced ? null : { severity: 'blocking', blocking: true, category: 'balancete', code } };
  return { registry_version: GENERATED_ENGINE_CONTRACT.registry_version, formula_version: GENERATED_ENGINE_CONTRACT.formula_version, statements, bp, indicators: balanced ? calculateIndicators(statements) : [] };
}
export function applyGeneratedBackendEliminations(gross, entries) {
  const result = { ...gross };
  for (const entry of entries) {
    const debit = GENERATED_BACKEND_REGISTRY.rubrics[entry.debit_canonical_key];
    const credit = GENERATED_BACKEND_REGISTRY.rubrics[entry.credit_canonical_key];
    result[entry.debit_canonical_key] = (result[entry.debit_canonical_key] || 0) + calculateJournalPresentationEffect({ rubric: debit, side: 'debit', amount: entry.amount });
    result[entry.credit_canonical_key] = (result[entry.credit_canonical_key] || 0) + calculateJournalPresentationEffect({ rubric: credit, side: 'credit', amount: entry.amount });
  }
  return result;
}
