import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

// BEGIN GENERATED ACTION PLAN TASK STATE
export function isActiveActionTask(task) {
  return task?.status !== 'cancelled'
    && (
      !task?.operation_status
      || task.operation_status === 'active'
    );
}
// END GENERATED ACTION PLAN TASK STATE

const VALID_APP_ROLES = new Set(['hq_admin','tenant_admin','consultant','client_viewer']);
const WRITE_ROLES = new Set(['hq_admin','tenant_admin','consultant']);
function resolveAppRole(user) { if (!user) return null; if (VALID_APP_ROLES.has(user.app_role)) return user.app_role; return user.role === 'admin' ? 'hq_admin' : null; }
function assertCanWrite(effectiveRole) { if (!WRITE_ROLES.has(effectiveRole)) throw Object.assign(new Error('Forbidden: write permission required'), { status: 403 }); }
async function readAllById(entity, query, order = 'id', pageSize = 500) { const rows=[]; let cursor=null; while (true) { const page=await entity.filter(cursor ? { ...query, id: { $gt: cursor } } : query, order, pageSize); if (!page.length) break; rows.push(...page); if (page.length < pageSize) break; cursor=page[page.length-1].id; } return rows; }
Deno.serve(async (req) => { try { const base44=createClientFromRequest(req); const user=await base44.auth.me(); if (!user) return Response.json({error:'Unauthorized'},{status:401}); const effectiveRole=resolveAppRole(user); assertCanWrite(effectiveRole); const { action_plan_id }=await req.json(); if (!action_plan_id) return Response.json({error:'action_plan_id is required'},{status:400}); const plan=await base44.asServiceRole.entities.ActionPlan.get(action_plan_id); if (!plan) return Response.json({error:'Action plan not found'},{status:404}); if (effectiveRole !== 'hq_admin' && plan.tenant_id !== user.tenant_id) return Response.json({error:'Forbidden: tenant mismatch'},{status:403}); const tasks=await readAllById(base44.asServiceRole.entities.ActionTask,{plan_id:plan.id,tenant_id:plan.tenant_id}); const active=tasks.filter(isActiveActionTask); const keys=new Set(); for (const task of active) { if (task.task_key && keys.has(task.task_key)) return Response.json({error:'ACTION_TASK_KEY_DUPLICATE'},{status:409}); if (task.task_key) keys.add(task.task_key); } for (const task of active) for (const key of task.dependency_task_keys || []) if (!keys.has(key)) return Response.json({error:'ACTION_TASK_DEPENDENCY_MISSING'},{status:409}); const today=new Date().toISOString().slice(0,10); const validWeights=active.every(t=>Number.isFinite(Number(t.priority_score))&&Number(t.priority_score)>0); const divisor=validWeights ? active.reduce((sum,t)=>sum+Number(t.priority_score),0) : active.length; const progress=divisor ? active.reduce((sum,t)=>sum+Number(t.progress_percentage||0)*(validWeights?Number(t.priority_score):1),0)/divisor : 0; const open=active.filter(t=>t.status!=='done'); const due=open.map(t=>t.due_date).filter(Boolean).sort(); const state={total_tasks:active.length,done_tasks:active.filter(t=>t.status==='done').length,blocked_tasks:active.filter(t=>t.status==='blocked'||t.is_blocked).length,overdue_tasks:open.filter(t=>t.due_date&&t.due_date<today).length,critical_open_tasks:open.filter(t=>t.priority==='critical').length,next_due_date:due[0]||null,overall_progress_percentage:Math.round(progress*100)/100,updated_at:new Date().toISOString(),updated_by:user.email}; await base44.asServiceRole.entities.ActionPlan.update(plan.id,state); const confirmed=await base44.asServiceRole.entities.ActionPlan.get(plan.id); if (!confirmed || confirmed.total_tasks!==state.total_tasks || confirmed.done_tasks!==state.done_tasks) throw new Error('ACTION_PLAN_RECALCULATION_CONFIRMATION_FAILED'); return Response.json({plan:confirmed,counts:{physical_tasks:tasks.length,active_tasks:active.length,...state},calculation_method:validWeights?'priority_weighted':'simple_average'}); } catch(error) { return Response.json({error:error.message},{status:error.status||500}); } });