#!/usr/bin/env node
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { pathToFileURL } from 'node:url';
import process from 'node:process';

const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm';
export const PHASE4_TEST_FILES = ['src/lib/__tests__/phase4-harness.test.js', 'src/lib/__tests__/phase4-scenario-harness.test.js', 'src/lib/__tests__/phase4-action-plan.test.js', 'src/lib/__tests__/phase4-task-history.test.js', 'src/lib/__tests__/phase4-review-lifecycle.test.js', 'src/lib/__tests__/phase4-review-concurrency.test.js', 'src/lib/__tests__/phase4-report-version.test.js', 'src/lib/__tests__/phase4-report-official.test.js', 'src/lib/__tests__/phase4-pdf-reproducibility.test.js', 'src/lib/__tests__/phase4-rbac.test.js', 'src/lib/__tests__/phase4-e2e-cycle.test.js', 'src/lib/__tests__/phase4-writer-matrix.test.js'];
const phase4Command = ['vitest', ['run', ...PHASE4_TEST_FILES]];
export const DEFAULT_STEPS = ['audit:backend-compile', 'audit:seg02', 'audit:rbac-functions', 'audit:phase5-routes', 'audit:phase5-query-scope', 'audit:phase5-production-surface', 'audit:phase5-product-readiness', 'test:phase2', 'test:phase3'].map((script) => [npm, ['run', script]]).concat([phase4Command], ['test:phase5', 'test:ci', 'lint', 'typecheck', 'build'].map((script) => [npm, ['run', script]]));
function treeSha(root = process.cwd()) { const excluded = new Set(['.git', 'node_modules', 'dist']); const files = []; const walk = (dir) => readdirSync(dir).sort().forEach((name) => { if (excluded.has(name)) return; const path = join(dir, name); statSync(path).isDirectory() ? walk(path) : files.push(path); }); walk(root); const hash = createHash('sha256'); files.forEach((path) => { hash.update(relative(root, path)); hash.update('\0'); hash.update(readFileSync(path)); hash.update('\0'); }); return hash.digest('hex'); }
function killTree(child) { if (!child.pid) return; try { process.kill(-child.pid, 'SIGKILL'); } catch { try { child.kill('SIGKILL'); } catch {} } }
export function executeStep(command, args, timeoutMs) { return new Promise((resolve) => { const child = spawn(command, args, { detached: true, stdio: ['ignore', 'pipe', 'pipe'] }); let timedOut = false; let stdout = ''; let stderr = ''; child.stdout.on('data', (chunk) => { const text = chunk.toString(); stdout += text; process.stdout.write(text); }); child.stderr.on('data', (chunk) => { const text = chunk.toString(); stderr += text; process.stderr.write(text); }); const timer = setTimeout(() => { timedOut = true; killTree(child); }, timeoutMs); child.once('exit', (code) => { clearTimeout(timer); killTree(child); resolve({ exit_code: timedOut ? null : code ?? 1, timed_out: timedOut, error: timedOut ? 'STEP_TIMEOUT' : code === 0 ? null : 'STEP_FAILED', stdout, stderr }); }); child.once('error', () => { clearTimeout(timer); resolve({ exit_code: 1, timed_out: false, error: 'STEP_SPAWN_ERROR', stdout, stderr }); }); }); }
export async function runVerify(steps = DEFAULT_STEPS, timeout = 120000) { const results = []; for (const [command, args] of steps) { const result = await executeStep(command, args, timeout); results.push({ command, args, ...result }); if (result.exit_code !== 0 || result.timed_out) break; } const summary = { verify_success: results.length === steps.length && results.every((result) => result.exit_code === 0 && !result.timed_out), total_steps: steps.length, completed_steps: results.length, results, tree_sha256: treeSha(), finished_at: new Date().toISOString() }; console.log(JSON.stringify(summary)); return { success: summary.verify_success, summary }; }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) { const steps = process.env.VERIFY_STEPS_JSON ? JSON.parse(process.env.VERIFY_STEPS_JSON) : DEFAULT_STEPS; const timeout = Number(process.env.VERIFY_TIMEOUT_MS || 120000); const result = await runVerify(steps, timeout); process.exitCode = result.success ? 0 : 1; }