import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

const VALID_APP_ROLES = new Set(['hq_admin', 'tenant_admin', 'consultant', 'client_viewer']);
const VERSIONED_ENTITIES = ['FinancialStatementLine', 'FinancialIndicatorSnapshot', 'FinancialValidationResult', 'FinancialMappingResolution', 'FinancialTrialBalanceLine', 'FinancialDfcCompositionLine', 'PreparedFinancialDatasetLine'];
const ENGINE_VERSION = 'FAL-FIN-LIFECYCLE-1.0.0';
const ENGINE_HASH = '8eb5018d13d3ebaab59985b504e7bda63bbbc9f5f9e75c5453d5c7a61dfc29e9';

function resolveAppRole(user) { return !user ? null : VALID_APP_ROLES.has(user.app_role) ? user.app_role : user.role === 'admin' ? 'hq_admin' : null; }
function canonicalize(value) { if (value === null || value === undefined || typeof value !== 'object') return value ?? null; if (Array.isArray(value)) return value.map(canonicalize); return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonicalize(value[key])])); }
async function hash(value) { const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(JSON.stringify(value))); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join(''); }
async function invokeEngine(base44, operation, input) { const response = await base44.functions.invoke('financialLifecycleDeterminismEngine', { contract_version: ENGINE_VERSION, operation, input }); const result = response?.data || response; if (!result?.success || result.engine_version !== ENGINE_VERSION || result.contract_hash !== ENGINE_HASH || result.operation !== operation || result.input_fingerprint !== await hash(input)) throw new Error('FINANCIAL_LIFECYCLE_ENGINE_CONTRACT_MISMATCH'); return result.decision; }
async function readAllById(entity, filter, pageSize = 500, startCursor = null) { const rows = []; let cursor = startCursor; let pagesRead = 0; while (true) { const page = await entity.filter(cursor ? { ...filter, id: { $gt: cursor } } : filter, 'id', pageSize); pagesRead += 1; if (!page.length) break; rows.push(...page); cursor = page.at(-1).id; if (page.length < pageSize) break; } return { rows, pagesRead }; }
function emptyDiagnosisDelta() { return { pages_read: 0, rows_read: 0, rows_updated: 0, rows_unchanged: 0, rows_ambiguous: 0, rows_failed: 0, source_heads_created: 0, source_heads_updated: 0, before_by_entity_status: {}, after_by_entity_status: {}, errors: [], ambiguous_rows: [] }; }
function initialStats(manifest) { return { pages_read: manifest?.pages_read || 0, rows_read: manifest?.rows_read || 0, rows_updated: manifest?.rows_updated || 0, rows_unchanged: manifest?.rows_unchanged || 0, rows_ambiguous: manifest?.rows_ambiguous || 0, rows_failed: manifest?.rows_failed || 0, source_heads_created: manifest?.source_heads_created || 0, source_heads_updated: manifest?.source_heads_updated || 0, before_by_entity_status: manifest?.before_by_entity_status || {}, after_by_entity_status: manifest?.after_by_entity_status || {}, errors: manifest?.errors || [], ambiguous_rows: manifest?.ambiguous_rows || [], diagnostics_migrated: manifest?.diagnostics_migrated || 0 }; }
function count(delta, bucket, entity, status) { const key = `${entity}:${status || 'missing'}`; delta[bucket][key] = Number(delta[bucket][key] || 0) + 1; }

Deno.serve(async (req) => {
  let base44; let workingManifest; let stats; let lastCursor = null;
  try {
    base44 = createClientFromRequest(req); const user = await base44.auth.me(); if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    const appRole = resolveAppRole(user); if (!['hq_admin', 'tenant_admin'].includes(appRole)) return Response.json({ error: 'Forbidden' }, { status: 403 });
    const { diagnosis_id = null, target_tenant_id = null, all_tenants = false, dry_run = true, resume_manifest_id = null } = await req.json();
    if (appRole === 'tenant_admin' && (all_tenants || (target_tenant_id && target_tenant_id !== user.tenant_id))) return Response.json({ error: 'TENANT_MISMATCH' }, { status: 403 });
    const tenantId = appRole === 'tenant_admin' ? user.tenant_id : target_tenant_id; const migrationKey = ['financial-output-lifecycle', 'v4', tenantId || 'all-tenants', diagnosis_id || 'all-diagnoses'].join('|');
    let existing = resume_manifest_id ? await base44.asServiceRole.entities.FinancialLifecycleMigrationManifest.get(resume_manifest_id) : null;
    if (!existing) existing = (await base44.asServiceRole.entities.FinancialLifecycleMigrationManifest.filter({ migration_key: migrationKey }, '-created_at', 10)).find((item) => ['running', 'partial'].includes(item.status)) || null;
    const query = diagnosis_id ? { id: diagnosis_id } : tenantId ? { tenant_id: tenantId } : {}; const startCursor = !diagnosis_id ? existing?.last_completed_cursor || existing?.last_cursor || null : null;
    const diagnosesResult = await readAllById(base44.asServiceRole.entities.FinancialDiagnosis, query, 500, startCursor); stats = initialStats(existing); stats.pages_read += diagnosesResult.pagesRead;
    const now = new Date().toISOString(); if (!dry_run) workingManifest = existing || await base44.asServiceRole.entities.FinancialLifecycleMigrationManifest.create({ tenant_id: tenantId || null, migration_key: migrationKey, migration_run_id: crypto.randomUUID(), attempt: Number(existing?.attempt || 0) + 1, status: 'running', before_counts: {}, after_counts: {}, ambiguous_rows: [], diagnostics_migrated: 0, errors: [], started_at: now, created_at: now, created_by: user.email, last_completed_cursor: startCursor, completed_diagnoses_count: stats.diagnostics_migrated });
    for (const diagnosis of diagnosesResult.rows) {
      const delta = emptyDiagnosisDelta();
      try {
        const [runsResult, uploadsResult, snapshotsResult, headsResult] = await Promise.all([readAllById(base44.asServiceRole.entities.FinancialProcessingRun, { financial_diagnosis_id: diagnosis.id }), readAllById(base44.asServiceRole.entities.FinancialUpload, { financial_diagnosis_id: diagnosis.id, is_current: true }), readAllById(base44.asServiceRole.entities.FinancialProcessingSnapshot, { financial_diagnosis_id: diagnosis.id }), readAllById(base44.asServiceRole.entities.FinancialSourceOutputHead, { financial_diagnosis_id: diagnosis.id })]);
        const runsById = new Map(runsResult.rows.map((run) => [run.id, run])); const snapshotsByRun = new Map(snapshotsResult.rows.filter((item) => item.status === 'active').map((item) => [item.financial_processing_run_id, item])); const headsByKey = new Map();
        for (const head of headsResult.rows) { if (headsByKey.has(head.source_key)) throw new Error('HEAD_AMBIGUOUS'); headsByKey.set(head.source_key, head); }
        const grouped = new Map();
        for (const upload of uploadsResult.rows.filter((item) => item.source_entity_id)) for (const run of runsResult.rows.filter((item) => item.financial_upload_id === upload.id && item.status === 'succeeded')) { const snapshot = snapshotsByRun.get(run.id); if (!snapshot || snapshot.output_checksum !== run.output_checksum) continue; const periods = await readAllById(base44.asServiceRole.entities.FinancialStatementLine, { financial_diagnosis_id: diagnosis.id, financial_upload_id: upload.id, processing_run_id: run.id, dataset_scope: 'individual', statement_code: 'BP', publication_status: { $in: ['active', 'candidate'] } }); delta.pages_read += periods.pagesRead; for (const period of [...new Set(periods.rows.map((row) => row.period).filter(Boolean))]) { const sourceKey = [diagnosis.id, upload.source_entity_id, period].join('|'); const candidate = { source_key: sourceKey, source_entity_id: upload.source_entity_id, source_period: period, financial_upload_id: upload.id, processing_run_id: run.id, snapshot_id: snapshot.id, snapshot_version_number: snapshot.version_number, run_completed_at: run.completed_at, snapshot_created_at: snapshot.created_at, run_status: run.status, snapshot_status: snapshot.status, run_output_checksum: run.output_checksum, snapshot_output_checksum: snapshot.output_checksum, run, snapshot }; grouped.set(sourceKey, [...(grouped.get(sourceKey) || []), candidate]); } }
        const currentSnapshot = diagnosis.current_processing_snapshot_id ? await base44.asServiceRole.entities.FinancialProcessingSnapshot.get(diagnosis.current_processing_snapshot_id) : null;
        const selectionInput = { diagnosis_current_run_id: currentSnapshot?.status === 'active' ? currentSnapshot.financial_processing_run_id : null, source_keys: [...grouped.entries()].map(([source_key, candidates]) => ({ source_key, existing_head: headsByKey.get(source_key) || null, candidates: candidates.map(({ run, snapshot, ...candidate }) => candidate) })) };
        const selection = await invokeEngine(base44, 'select_current_legacy_candidates', selectionInput); const ambiguous = selection.ambiguous_source_keys || []; const blocked = ambiguous.length > 0;
        for (const item of ambiguous) { delta.rows_ambiguous += 1; delta.ambiguous_rows.push({ entity: 'FinancialSourceOutputHead', diagnosis_id: diagnosis.id, source_key: item.source_key, candidate_run_ids: item.candidate_run_ids, reason: 'HEAD_AMBIGUOUS' }); }
        const currentRunIds = new Set();
        if (!blocked) for (const [sourceKey, selected] of Object.entries(selection.selected_by_source_key || {})) { currentRunIds.add(selected.processing_run_id); const candidate = grouped.get(sourceKey).find((item) => item.processing_run_id === selected.processing_run_id && item.snapshot_id === selected.snapshot_id); const data = { tenant_id: diagnosis.tenant_id, financial_diagnosis_id: diagnosis.id, source_entity_id: candidate.source_entity_id, source_period: candidate.source_period, source_key: candidate.source_key, financial_upload_id: candidate.financial_upload_id, current_processing_run_id: candidate.processing_run_id, current_processing_snapshot_id: candidate.snapshot_id, current_input_checksum: candidate.run.input_checksum || null, current_output_checksum: candidate.snapshot_output_checksum, mapping_checksum: candidate.snapshot.mapping_checksum || null, registry_hash: candidate.snapshot.registry_hash || null, formula_version: candidate.snapshot.formula_version || null, status: 'active', updated_at: now, updated_by: user.email }; if (!dry_run) { const previous = headsByKey.get(sourceKey); if (previous) { await base44.asServiceRole.entities.FinancialSourceOutputHead.update(previous.id, data); delta.source_heads_updated += 1; } else { await base44.asServiceRole.entities.FinancialSourceOutputHead.create(data); delta.source_heads_created += 1; } } }
        for (const entityName of VERSIONED_ENTITIES) { const result = await readAllById(base44.asServiceRole.entities[entityName], { financial_diagnosis_id: diagnosis.id }); delta.pages_read += result.pagesRead; delta.rows_read += result.rows.length; const updates = []; for (const row of result.rows) { count(delta, 'before_by_entity_status', entityName, row.publication_status); if (blocked) continue; const run = runsById.get(row.processing_run_id); const publication_status = currentRunIds.has(row.processing_run_id) ? 'active' : run?.status === 'succeeded' ? 'superseded' : run && ['failed', 'partial_failed', 'cancelled'].includes(run.status) ? 'invalid' : null; if (!publication_status) { delta.rows_ambiguous += 1; delta.ambiguous_rows.push({ entity: entityName, id: row.id, diagnosis_id: diagnosis.id, reason: 'LEGACY_AMBIGUOUS' }); continue; } if (publication_status === row.publication_status) delta.rows_unchanged += 1; else updates.push({ id: row.id, publication_status, ...(publication_status === 'active' ? { published_at: now } : publication_status === 'superseded' ? { superseded_at: now } : { invalidated_at: now, invalidation_reason: 'MIGRATION_RUN_STATUS' }) }); } if (!dry_run && !blocked) for (let index = 0; index < updates.length; index += 500) await base44.asServiceRole.entities[entityName].bulkUpdate(updates.slice(index, index + 500)); delta.rows_updated += dry_run || blocked ? 0 : updates.length; }
        if (!dry_run) for (const entityName of VERSIONED_ENTITIES) { const after = await readAllById(base44.asServiceRole.entities[entityName], { financial_diagnosis_id: diagnosis.id }); for (const row of after.rows) count(delta, 'after_by_entity_status', entityName, row.publication_status); } else delta.after_by_entity_status = structuredClone(delta.before_by_entity_status);
        const merged = await invokeEngine(base44, 'merge_migration_diagnosis_delta', { accumulated_stats: stats, diagnosis_delta: delta, diagnosis_completed: true, previous_cursor: lastCursor, new_cursor: diagnosis.id }); stats = merged.accumulated_stats; lastCursor = merged.last_completed_cursor;
        if (workingManifest) await base44.asServiceRole.entities.FinancialLifecycleMigrationManifest.update(workingManifest.id, { ...stats, before_counts: stats.before_by_entity_status, after_counts: stats.after_by_entity_status, status: 'running', current_diagnosis_id: diagnosis.id, last_cursor: lastCursor, last_completed_cursor: lastCursor, completed_diagnoses_count: stats.diagnostics_migrated, completed_at: null });
      } catch (error) {
        const merged = await invokeEngine(base44, 'merge_migration_diagnosis_delta', { accumulated_stats: stats, diagnosis_delta: delta, diagnosis_completed: false, previous_cursor: lastCursor, new_cursor: diagnosis.id }); stats = { ...merged.accumulated_stats, errors: [...(merged.accumulated_stats.errors || []), { diagnosis_id: diagnosis.id, message: error.message }] }; if (workingManifest) await base44.asServiceRole.entities.FinancialLifecycleMigrationManifest.update(workingManifest.id, { ...stats, status: 'partial', current_diagnosis_id: diagnosis.id, last_cursor: lastCursor, last_completed_cursor: lastCursor, before_counts: stats.before_by_entity_status, after_counts: stats.after_by_entity_status, completed_at: null }); if (dry_run) throw error; return Response.json({ error: error.message, manifest_id: workingManifest.id, status: 'partial' }, { status: 500 });
      }
    }
    const status = stats.rows_ambiguous ? 'completed_with_ambiguities' : 'completed'; const manifest = { ...stats, tenant_id: tenantId || null, migration_key: migrationKey, migration_run_id: workingManifest?.migration_run_id || crypto.randomUUID(), attempt: workingManifest?.attempt || 1, status, before_counts: stats.before_by_entity_status, after_counts: stats.after_by_entity_status, last_cursor: lastCursor, last_completed_cursor: lastCursor, completed_diagnoses_count: stats.diagnostics_migrated, completed_at: new Date().toISOString(), created_at: workingManifest?.created_at || now, created_by: user.email };
    const persisted = dry_run ? null : await base44.asServiceRole.entities.FinancialLifecycleMigrationManifest.update(workingManifest.id, manifest); return Response.json({ success: true, dry_run, manifest_id: persisted?.id || null, ...manifest });
  } catch (error) { return Response.json({ error: error.message }, { status: error.message === 'FINANCIAL_LIFECYCLE_ENGINE_CONTRACT_MISMATCH' ? 409 : 500 }); }
});